### ISSUE TITLE
Overidig default uikit.css

### ISSUE THREAD

**Issue by c001os** [fedorae-com/nuxt-uikit#15]
Hi!

I added my own customized css into my nuxtconfig, but the fonts and another styles not overriding the default uikit styles.

Here is my nuxt.config.tc:

`export default defineNuxtConfig({
    css: ["~/assets/css/theme.css"],
    modules: [
      '@fedorae/nuxt-uikit'
    ],

})`

Any solution, or where i go wrong?
Thanx a lot!

**Comment by swalx** [comment]
Hey @c001os 

That should be the default behavior. Are you able to provide a reproduction link that I may look further into this?

I have tested this locally with custom styles and the defaults were overridden.

**Comment by c001os** [comment]
Sorry but i havent a public link for now. 
I get rid of this whit he ugly solution, using this on every .vue template file:
`<style scoped>
        @import '~/assets/css/theme.css';
</style>`

**Comment by swalx** [comment]
No problem.

Thank you, that may be useful to anyone else having this issue.

Unfortunately I have not been able to reproduce the issue with the tests I've done so far. However, I will definitely keep on eye on this. 

Closing this issue, please feel free to reopen if there are any new developments regarding same.

**Comment by remifreriks** [comment]
We have the same issue. UiKit is on the dev environment loaded after the default scss making uikit override everything.

**Comment by swalx** [comment]
@remi-freriks are you able to produce a reproduction for this error?

**Comment by remifreriks** [comment]
[Here](https://bluetree.bekijk.link/) you can see the reproduction of the error. In the inspector you can see that uikit is loaded after the app.scss. We loaded css and nuxt-uikit in the following way:

export default defineNuxtConfig({
    css: ["@/assets/scss/app.scss"],
    modules: [
      '@fedorae/nuxt-uikit',

.....

**Comment by sightorld** [comment]
Repo with the reproduction of the issue [here](https://github.com/sightorld/SCSSLoadingIssueRepo)
Tested combinations: 
- Loading module and main.scss as 'css' property in nuxt config
- Loading module and main.scss as Vite preprocessor property in nuxt config 
In both options the stylesheet is loaded for a split second then gets overridden by the module (if the @imports are excluded from main.css even that doesn't happen)

**Comment by swalx** [comment]
> [Here](https://bluetree.bekijk.link/) you can see the reproduction of the error. In the inspector you can see that uikit is loaded after the app.scss. We loaded css and nuxt-uikit in the following way:
> 
> export default defineNuxtConfig({ css: ["@/assets/scss/app.scss"], modules: [ '@fedorae/nuxt-uikit',
> 
> .....

@remi-freriks reproduction link is locked with basic auth.

**Comment by swalx** [comment]
> Repo with the reproduction of the issue [here](https://github.com/sightorld/SCSSLoadingIssueRepo) Tested combinations:
> 
>     * Loading module and main.css as 'css' property in nuxt config
> 
>     * Loading module and main.css as Vite preprocessor property in nuxt config
>       In both options the stylesheet is loaded for a split second then gets overridden by the module (if the @imports are excluded from main.css even that doesn't happen)

@sightorld Looking into this, will get back with an update as soon as possible.

**Comment by remifreriks** [comment]
> > [Here](https://bluetree.bekijk.link/) you can see the reproduction of the error. In the inspector you can see that uikit is loaded after the app.scss. We loaded css and nuxt-uikit in the following way:
> > export default defineNuxtConfig({ css: ["@/assets/scss/app.scss"], modules: [ '@fedorae/nuxt-uikit',
> > .....
> 
> @remi-freriks reproduction link is locked with basic auth.

Basic Auth has now been removed

**Comment by swalx** [comment]
@sightorld, @remi-freriks  the issue is now identified. However, it seems to be something that affects UI modules in general because of how the css is added into the Nuxt app.

See:
https://stackoverflow.com/questions/64229346/nuxt-how-to-override-global-css-for-a-page
https://github.com/nuxt-community/vuetify-module/issues/176

The workaround provided by @c001os will address the issue but as was mentioned, you will need to add the import or src in each .vue file or at least in a layout file.

```css
<style src="~/assets/scss/main.scss" lang="scss" scoped>
</style>
/* or */
<style lang="scss" scoped>
@import '~/assets/scss/app.scss'
</style>
```
@sightorld based on the reproduction provided, a solution could be to add an option to use the scss/less styles as the default instead of the normal css; since that seems to be your main objective. However, for the fonts I was unable to reproduce a particular desired behaviour. I would suggest adding the fonts URL to the head property of the Nuxt app in the nuxt.config or use the `@mdi/font` library then add as a Nuxt plugin.

`@mdi/font` example usage: https://edu.fedorae.com/better-way-to-add-vuetify3-to-nuxt3/

```ts
head: [
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto'}
    ],
```

We are still looking into this and if there are better solutions we will add to a release.

**Comment by remifreriks** [comment]
Okay, so loading css via the nuxt config doesn't work. To do this via layouts is a great solution for us. Does this have any drawbacks with compiling css?

**Comment by swalx** [comment]
> Okay, so loading css via the nuxt config doesn't work. To do this via layouts is a great solution for us. Does this have any drawbacks with compiling css?

None that I am aware of. The css file, while it may be imported into multiple different components should only be treated as a single import.

See links below to questions of similar nature:
https://stackoverflow.com/questions/73596913/what-happens-if-two-components-import-the-same-css-file-in-react
https://stackoverflow.com/questions/11256637/does-importing-same-css-file-multiple-times-add-any-performance-issues

As mentioned in one of the answers, the bundler should be able to effectively handle numerous imports of same file.
