### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'css') 

### ISSUE THREAD

**Issue by Ulrich-Mbouna** [fedorae-com/nuxt-uikit#7]
Hi Thanks for this modules, but i face some issues:

- Nuxt version : 3.1.1
- nuxt-uikit verrsion : 2.0.11

When i run npm install or npm run dev, i face yhis issue : ` Cannot start nuxt:  Cannot read properties of undefined (reading 'css') `

Thank you for your help.

**Comment by swalx** [comment]
Thank you for bring this issue to our attention.

Please use ```yarn add -D nuxt-uikit@next``` to install the beta version compatible with Nuxt 3 as nuxt-uikit version 2.0.11 is only for Nuxt 2.

The beta version has the following known issues:
- No icon support
- Blank page when set ssr: false

We have updated the README.md file to reflect the correct installation information and are working to have these issues resolved in the shortest time possible.

Thanks for using this module and please feel free to report any and all other issues that you may find for us to better improve this module.

Closing this issue.
